#!/bin/bash
SRC=/Users/jmn/.virtualenvs/cv/src
DST=root@192.168.1.2
filename=${1:-$SRC}
ip=${2:-$DST}
ssh $ip mkdir /home/pi/Documents/RocketProject
scp -r $filename $ip:/home/pi/Documents/RocketProject